[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
ffi = false
fuzz = { runs = 256 }

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[dependencies]
forge-std = { version = "1.9.4", git = "https://github.com/foundry-rs/forge-std.git", tag = "v1.9.4" }
account-abstraction = { version = "0.7.0", git = "https://github.com/eth-infinitism/account-abstraction.git", tag = "v0.7.0" }
